"""Descrição da migração

Revision ID: 59e8aa50702f
Revises: 9c36dc57e5a8
Create Date: 2025-02-13 02:40:10.859610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e8aa50702f'
down_revision = '9c36dc57e5a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Administrador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('nome_barbearia', sa.String(length=100), nullable=False))
        batch_op.drop_column('nome')

    with op.batch_alter_table('Agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Administrador', ['admin_id'], ['id_administrador'])

    with op.batch_alter_table('Funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Administrador', ['admin_id'], ['id_administrador'])
        batch_op.drop_column('senha')

    with op.batch_alter_table('Horarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Administrador', ['admin_id'], ['id_administrador'])

    with op.batch_alter_table('Servicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Administrador', ['admin_id'], ['id_administrador'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Servicos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('admin_id')

    with op.batch_alter_table('Horarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('admin_id')

    with op.batch_alter_table('Funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('admin_id')

    with op.batch_alter_table('Agendamentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('admin_id')

    with op.batch_alter_table('Administrador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('nome_barbearia')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
