"""Primeiro esquema de tabelas do Database

Revision ID: 9c36dc57e5a8
Revises: 
Create Date: 2025-01-30 03:03:50.387756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c36dc57e5a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Administrador',
    sa.Column('id_administrador', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_administrador')
    )
    op.create_table('Funcionarios',
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_funcionario')
    )
    op.create_table('Servicos',
    sa.Column('id_servico', sa.Integer(), nullable=False),
    sa.Column('nome_servico', sa.String(length=100), nullable=False),
    sa.Column('valor_servico', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tempo_servico', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_servico')
    )
    op.create_table('Horarios',
    sa.Column('id_horario', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.Column('preenchido', sa.Boolean(), nullable=False),
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_funcionario'], ['Funcionarios.id_funcionario'], ),
    sa.PrimaryKeyConstraint('id_horario')
    )
    op.create_table('Agendamentos',
    sa.Column('id_agendamento', sa.Integer(), nullable=False),
    sa.Column('id_horario', sa.Integer(), nullable=False),
    sa.Column('id_servico', sa.Integer(), nullable=False),
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.Column('nome_cliente', sa.String(length=100), nullable=False),
    sa.Column('telefone_cliente', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_funcionario'], ['Funcionarios.id_funcionario'], ),
    sa.ForeignKeyConstraint(['id_horario'], ['Horarios.id_horario'], ),
    sa.ForeignKeyConstraint(['id_servico'], ['Servicos.id_servico'], ),
    sa.PrimaryKeyConstraint('id_agendamento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Agendamentos')
    op.drop_table('Horarios')
    op.drop_table('Servicos')
    op.drop_table('Funcionarios')
    op.drop_table('Administrador')
    # ### end Alembic commands ###
