"""Agora o agendamento recebe o nome do barbeiro

Revision ID: cecb82e9e160
Revises: 59e8aa50702f
Create Date: 2025-02-14 01:05:25.333279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cecb82e9e160'
down_revision = '59e8aa50702f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_funcionario', sa.String(length=100), nullable=False))
        batch_op.drop_constraint('Agendamentos_id_funcionario_fkey', type_='foreignkey')
        batch_op.drop_column('id_funcionario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_funcionario', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('Agendamentos_id_funcionario_fkey', 'Funcionarios', ['id_funcionario'], ['id_funcionario'])
        batch_op.drop_column('nome_funcionario')

    # ### end Alembic commands ###
